version: '3.8'

services:
  popchainswap:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: popchainswap
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CHAIN_ID=7257
      - NEXT_PUBLIC_USE_CUSTOM_LOGO=true
      - NEXT_PUBLIC_NODE_PRODUCTION=https://rpc.popchain.ai
    volumes:
      # 挂载logo文件 (可选，如果需要动态更新)
      - ./apps/web/public/logo.png:/app/public/logo.png:ro
      - ./apps/web/public/logoWIthText.png:/app/public/logoWIthText.png:ro
      - ./apps/web/public/logoWIthTextBlack.png:/app/public/logoWIthTextBlack.png:ro
    networks:
      - popchain-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: popchainswap-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL证书目录
    depends_on:
      - popchainswap
    networks:
      - popchain-network

networks:
  popchain-network:
    driver: bridge

# 使用方法:
# 1. 构建并启动: docker-compose up -d
# 2. 查看日志: docker-compose logs -f popchainswap
# 3. 重启服务: docker-compose restart popchainswap
# 4. 停止服务: docker-compose down
